### ISSUE TITLE
Bigint needs to return binary data

### ISSUE THREAD

**Issue by w4454962** [QuasarApp/mini-gmp#20]
std::string hex = "0907D8AF90186095EFBF55320D4B6B5EEEA339DA";
BigInt big(hex, 16)

if ( hex == big.getString(-16))   // = false   big.getString(-16) = "907D8AF90186095EFBF55320D4B6B5EEEA339DA"  
The expression does not hold

std::string hex2 = "00010001";
BigInt big2(hex2, 16)

if ( hex2 == big2.getString(-16))   // = false   big2.getString(-16) = "10001"  
The expression does not hold

**Comment by EndrII** [comment]
hi 
why are you using negative numbers?   big.getString(-16)
may be  big.getString(16)
```
std::string hex = "0907D8AF90186095EFBF55320D4B6B5EEEA339DA";
std::string hex2 = "00010001";
```
Your test cases is wrong because the first zero(s) is insignificant. 
The library will never guess how many zeros it needs to put in front.

if I understand correctly, you want to add a method that will return you raw data of number?

**Comment by w4454962** [comment]
![222222](https://user-images.githubusercontent.com/24670862/116645314-25e07900-a9a8-11eb-9670-7ade313b33fe.png)

Is it strange that hexadecimal text is singular


-16 is upper case hexadecimal
16 is lowercase hexadecimal
